# Generated by Django 2.2 on 2019-04-14 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sessionlog',
            old_name='mentor_id',
            new_name='mentor',
        ),
        migrations.RenameField(
            model_name='sessionlog',
            old_name='student_id',
            new_name='student',
        ),
    ]
