# Generated by Django 2.2 on 2019-04-14 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0002_auto_20190414_2222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sessionlog',
            name='duration_in_mins',
        ),
    ]
