# Generated by Django 2.2 on 2019-04-15 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0003_remove_sessionlog_duration_in_mins'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionlog',
            name='feeling',
            field=models.TextField(choices=[('excellent', "Excellent - It's going great."), ('average', 'Average - The student is moving at an acceptable pace.'), ('poor', "I'm worried about this student's progress.")]),
        ),
        migrations.AlterField(
            model_name='sessionlog',
            name='types',
            field=models.CharField(choices=[('intro', 'Intro'), ('inception', 'Project inception'), ('middle', 'Middle of project'), ('end', 'End of project'), ('prep', 'Interview preparation and career advice'), ('other', 'Other'), ('no-show', '**No-show**')], max_length=255),
        ),
    ]
