# Generated by Django 2.2 on 2019-04-15 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0004_auto_20190415_0159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionlog',
            name='date',
            field=models.DateField(),
        ),
    ]
