# Generated by Django 2.2 on 2019-07-06 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0006_auto_20190415_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionlog',
            name='projects',
            field=models.CharField(default='[other]', max_length=255),
        ),
    ]
