# Generated by Django 2.2 on 2019-07-06 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0007_sessionlog_projects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionlog',
            name='projects',
            field=models.CharField(default='["other"]', max_length=255),
        ),
    ]
