# Generated by Django 2.2 on 2019-07-16 14:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('student', '0003_student_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(choices=[('userCentric', 'User Centric Front End Development'), ('interactive', 'Interactive Front End Development'), ('dataCentric', 'Data Centric Development'), ('fullStack', 'Full Stack Frameworks with Django'), ('other', 'Other')], max_length=255)),
                ('score', models.IntegerField()),
                ('summary', models.TextField(default='', max_length=500)),
                ('mentor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.Student')),
            ],
        ),
    ]
