# Generated by Django 2.2 on 2019-04-14 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='mentor_id',
            new_name='mentor',
        ),
    ]
